"""
Heuristic Shadow Agent - Script Generator
Converts discovered workflow patterns into executable PyAutoGUI automation scripts
via LLM code synthesis with safety wrappers.
"""

import logging
import json
import re
import os
from datetime import datetime
from typing import Optional

from src.ai.llm_client import LLMClient
from src.db.database import db_manager
from src.db.models import AutomationScript, DetectedPattern
from config import Config

logger = logging.getLogger(__name__)


SCRIPT_GENERATION_PROMPT = """You are an expert Python automation engineer for the "Heuristic Shadow" desktop agent.
Your task: generate a safe, executable PyAutoGUI-based Python script that replicates a detected user workflow.

## Workflow Pattern
The user repeatedly performs these steps:
{pattern_description}

## Requirements
1. **Safety First**: Include `pyautogui.FAILSAFE = True` at the top.
2. **Wait times**: Add `pyautogui.sleep(0.5)` between actions to avoid overwhelming the system.
3. **Error handling**: Wrap the main logic in try/except with a graceful cleanup.
4. **Window focus**: If switching between apps, use `pygetwindow` or Alt+Tab to focus the right window.
5. **Comment everything**: Each step must have a clear comment.
6. **Self-contained**: The script must be a single `.py` file that can run standalone.
7. **Return the COMPLETE Python script, nothing else.** Wrap in ```python ... ``` code block.

## Example Output Format
```python
\"""
Auto-generated by Heuristic Shadow Agent.
Pattern: [pattern name]
Generated: [timestamp]
\"""
import pyautogui
import time
import sys

pyautogui.FAILSAFE = True

def main():
    try:
        # Step 1: Switch to source application
        pyautogui.hotkey('alt', 'tab')
        pyautogui.sleep(0.5)
        
        # Step 2: Select all text
        pyautogui.hotkey('ctrl', 'a')
        pyautogui.sleep(0.3)
        
        # Step 3: Copy
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.sleep(0.3)
        
        # ... more steps ...
        
        print("Automation completed successfully.")
    except KeyboardInterrupt:
        print("Automation cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"Automation error: {{e}}")
        sys.exit(1)

if __name__ == "__main__":
    main()
```

Now generate the script for this pattern:
"""


class ScriptGenerator:
    """Generates automation scripts from detected patterns using LLM."""

    def __init__(self):
        self.llm = LLMClient()
        self.output_dir = Config.SCRIPTS_DIR
        os.makedirs(self.output_dir, exist_ok=True)

    # ------------------------------------------------------------------
    # Script generation
    # ------------------------------------------------------------------

    def generate_script(
        self,
        pattern: dict,
        dry_run: bool = True,
    ) -> Optional[str]:
        """
        Generate a PyAutoGUI script for a detected pattern.

        Args:
            pattern: DetectedPattern dict with sequence_json, pattern_name, etc.
            dry_run: If True, only generate without persisting.

        Returns:
            Generated Python code string, or None on failure.
        """
        pattern_name = pattern.get("pattern_name", "Unnamed Pattern")
        sequence = self._parse_sequence(pattern.get("sequence_json", "[]"))
        pattern_hash = pattern.get("pattern_hash", "")

        logger.info(
            f"Generating script for pattern '{pattern_name}' "
            f"({len(sequence)} steps, hash={pattern_hash})"
        )

        # Build human-readable pattern description for the LLM
        description = self._build_pattern_description(sequence, pattern_name)

        # Generate via LLM
        prompt = SCRIPT_GENERATION_PROMPT.format(
            pattern_description=description
        )

        try:
            response = self.llm.chat(
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                max_tokens=4096,
            )

            # Extract code from response
            code = self._extract_code_block(response.content)
            if not code:
                logger.error("LLM response contained no code block.")
                return None

            # Validate and enhance
            code = self._enhance_script(code, pattern_name, pattern_hash)

            if not dry_run:
                self._save_script(pattern, code)

            logger.info(f"Script generated: {len(code)} chars, via {response.provider}")
            return code

        except Exception as e:
            logger.error(f"Script generation failed: {e}")
            return None

    def generate_script_simple(self, sequence_steps: list, description: str = "") -> Optional[str]:
        """
        Generate a script from a simple step list (without a full pattern object).
        Useful for manual triggers.
        """
        description_text = description or "\n".join(
            f"{i+1}. {step}" for i, step in enumerate(sequence_steps)
        )

        prompt = SCRIPT_GENERATION_PROMPT.format(pattern_description=description_text)

        try:
            response = self.llm.chat(
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                max_tokens=4096,
            )
            code = self._extract_code_block(response.content)
            if code:
                code = self._enhance_script(code, "Manual Pattern", "")
            return code
        except Exception as e:
            logger.error(f"Simple script generation failed: {e}")
            return None

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_sequence(sequence_json: str) -> list:
        """Parse sequence JSON string to list."""
        try:
            if isinstance(sequence_json, str):
                return json.loads(sequence_json)
            return sequence_json
        except (json.JSONDecodeError, TypeError):
            return []

    def _build_pattern_description(self, sequence: list, name: str) -> str:
        """Build a human-readable description of the pattern for the LLM prompt."""
        lines = [f"**Pattern Name:** {name}", f"**Total Steps:** {len(sequence)}", ""]

        for i, step in enumerate(sequence, 1):
            if isinstance(step, str):
                # Parse token format like "CLICK:chrome.exe" or "SWITCH:notepad.exe"
                if ":" in step:
                    action, app = step.split(":", 1)
                    action_desc = {
                        "CLICK": "Click in",
                        "KEY": "Type in",
                        "HOTKEY": "Use keyboard shortcut in",
                        "SWITCH": "Switch to application",
                        "COPY": "Copy from",
                        "PASTE": "Paste to",
                        "ENTER": "Press Enter in",
                        "TAB": "Press Tab in",
                    }.get(action, action)
                    lines.append(f"{i}. {action_desc} **{app}**")
                else:
                    lines.append(f"{i}. {step}")
            elif isinstance(step, dict):
                lines.append(
                    f"{i}. {step.get('type', 'unknown')} at "
                    f"({step.get('x', '?')}, {step.get('y', '?')})"
                )

        return "\n".join(lines)

    @staticmethod
    def _extract_code_block(text: str) -> Optional[str]:
        """Extract Python code from an LLM response."""
        # Try ```python ... ``` block first
        pattern = r"```python\s*\n(.*?)```"
        match = re.search(pattern, text, re.DOTALL)
        if match:
            return match.group(1).strip()

        # Try generic ``` ... ``` block
        pattern = r"```\s*\n(.*?)```"
        match = re.search(pattern, text, re.DOTALL)
        if match:
            code = match.group(1).strip()
            # Verify it looks like Python
            if "import" in code or "def " in code or "pyautogui" in code:
                return code

        # Fallback: return the raw text if it looks like code
        if "pyautogui" in text and ("import" in text or "def " in text):
            return text.strip()

        return None

    def _enhance_script(
        self, code: str, pattern_name: str, pattern_hash: str
    ) -> str:
        """Add safety headers and metadata to the generated script."""
        header = f'''"""
Auto-generated by Heuristic Shadow Agent v{Config.APP_VERSION}
Pattern: {pattern_name}
Hash: {pattern_hash}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
WARNING: Contains PyAutoGUI automation. Move mouse to screen corner to abort.
"""

import pyautogui
import time
import sys
import logging

# --- Safety Configuration ---
pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0.3

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

'''

        # Remove existing import lines to avoid duplicates
        code_clean = re.sub(
            r'^import (pyautogui|time|sys|logging).*$\n?',
            '',
            code,
            flags=re.MULTILINE,
        )
        code_clean = re.sub(
            r'^from logging import.*$\n?',
            '',
            code_clean,
            flags=re.MULTILINE,
        )
        code_clean = re.sub(
            r'^pyautogui\.FAILSAFE.*$\n?',
            '',
            code_clean,
            flags=re.MULTILINE,
        )
        code_clean = re.sub(
            r'^pyautogui\.PAUSE.*$\n?',
            '',
            code_clean,
            flags=re.MULTILINE,
        )

        return header + "\n" + code_clean.strip()

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _save_script(self, pattern: dict, code: str) -> Optional[int]:
        """Save generated script to database and filesystem."""
        pattern_name = pattern.get("pattern_name", "unnamed")
        pattern_id = pattern.get("id")
        pattern_hash = pattern.get("pattern_hash", "")

        # Sanitize filename
        safe_name = re.sub(r'[^\w\s-]', '', pattern_name).strip()[:50]
        safe_name = safe_name.replace(' ', '_').lower()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_name}_{timestamp}.py"
        filepath = os.path.join(self.output_dir, filename)

        try:
            # Save to filesystem
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(code)
            logger.info(f"Script saved: {filepath}")

            # Save to database
            with db_manager.get_session() as session:
                script = AutomationScript(
                    pattern_id=pattern_id,
                    script_name=pattern_name,
                    script_description=f"Auto-generated from pattern {pattern_hash}",
                    python_code=code,
                    is_active=False,
                )
                session.add(script)
                session.flush()
                script_id = script.id

            # Update pattern status to 'ready'
            from src.core.pattern_miner import PatternMiner
            miner = PatternMiner()
            miner.update_pattern_status(pattern_hash, "ready")

            return script_id

        except Exception as e:
            logger.error(f"Failed to save script: {e}")
            return None

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def get_scripts(self, active_only: bool = False) -> list:
        """Retrieve generated scripts from the database."""
        try:
            with db_manager.get_session() as session:
                query = session.query(AutomationScript)
                if active_only:
                    query = query.filter_by(is_active=True)
                scripts = query.order_by(AutomationScript.created_at.desc()).all()
                return [s.to_dict() for s in scripts]
        except Exception as e:
            logger.error(f"Failed to fetch scripts: {e}")
            return []

    def get_script_by_id(self, script_id: int) -> Optional[dict]:
        """Get a specific script by ID."""
        try:
            with db_manager.get_session() as session:
                script = session.query(AutomationScript).filter_by(id=script_id).first()
                return script.to_dict() if script else None
        except Exception as e:
            logger.error(f"Failed to fetch script {script_id}: {e}")
            return None

    def toggle_script_active(self, script_id: int, active: bool) -> bool:
        """Enable or disable a script."""
        try:
            with db_manager.get_session() as session:
                script = session.query(AutomationScript).filter_by(id=script_id).first()
                if script:
                    script.is_active = active
                    return True
                return False
        except Exception as e:
            logger.error(f"Failed to toggle script: {e}")
            return False

    def delete_script(self, script_id: int) -> bool:
        """Delete a script from the database."""
        try:
            with db_manager.get_session() as session:
                script = session.query(AutomationScript).filter_by(id=script_id).first()
                if script:
                    session.delete(script)
                    return True
                return False
        except Exception as e:
            logger.error(f"Failed to delete script: {e}")
            return False
